# Generated by Django 5.0.3 on 2025-04-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="tags",
            field=models.ManyToManyField(db_index=True, to="book.tag"),
        ),
    ]
