# Generated by Django 5.0.3 on 2025-04-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0004_book_created_at_book_deleted_at_book_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default="2025-04-01"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, default="2025-04-01"),
            preserve_default=False,
        ),
    ]
