# Generated by Django 5.0.3 on 2025-06-04 18:00

import apps.mediahub.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediahub", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(upload_to=apps.mediahub.models.upload_to),
        ),
    ]
