# Generated by Django 5.0.3 on 2025-04-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_processing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedimage",
            name="large",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/large/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="medium",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/medium/"),
        ),
        migrations.AddField(
            model_name="uploadedimage",
            name="output_format",
            field=models.CharField(
                choices=[("JPEG", "JPEG"), ("WEBP", "WebP")],
                default="JPEG",
                max_length=10,
            ),
        ),
    ]
