# Generated by Django 5.0.3 on 2025-06-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HttpCallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("method", models.CharField(max_length=10)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Tempo em segundos", null=True
                    ),
                ),
                ("response_body", models.TextField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
