# Generated by Django 5.0.3 on 2025-06-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="httpcalllog",
            name="request_type",
            field=models.CharField(
                choices=[("success", "success"), ("error", "error")],
                default="error",
                max_length=20,
            ),
        ),
    ]
