# Generated by Django 5.0.3 on 2025-04-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_coursepayment_courserating"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
