# Generated by Django 5.0.3 on 2025-05-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mailer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="context",
            field=models.JSONField(null=True),
        ),
    ]
