# Generated by Django 5.0.3 on 2025-06-27 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManagerSheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("file", models.FileField(upload_to="sheet_uploads/")),
                ("formatter", models.JSONField(blank=True, null=True)),
                ("table_html", models.TextField(blank=True, null=True)),
                (
                    "type_of_data",
                    models.CharField(
                        choices=[("financial_data", "financial_data")],
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SheetPureData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type_data",
                    models.CharField(
                        choices=[("header", "Header"), ("body", "Body")],
                        default="body",
                        max_length=10,
                    ),
                ),
                ("sheet_line", models.JSONField(blank=True, null=True)),
                ("sanitized", models.BooleanField(default=False)),
                (
                    "manager_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pure_data",
                        to="sheet_manager.managersheet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SheetSanitizedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, db_index=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type_data",
                    models.CharField(
                        choices=[("header", "Header"), ("body", "Body")],
                        default="body",
                        max_length=10,
                    ),
                ),
                ("sheet_line", models.JSONField(blank=True, null=True)),
                (
                    "manager_sheet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sanitized_data",
                        to="sheet_manager.managersheet",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
