# Generated by Django 5.0.3 on 2025-05-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KnowledgeTopic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("fundamental", "Fundamental"),
                            ("intermediate", "Intermediário"),
                            ("advanced", "Avançado"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_recommended", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["level", "title"],
            },
        ),
    ]
