# Generated by Django 5.0.3 on 2024-03-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Profile", "verbose_name_plural": "Profiles"},
        ),
        migrations.RemoveField(
            model_name="profile",
            name="location",
        ),
        migrations.AddField(
            model_name="profile",
            name="access_level",
            field=models.CharField(
                choices=[("user", "user"), ("manager", "manager"), ("admin", "admin")],
                default="user",
                max_length=25,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="confirm_email",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
