# Generated by Django 5.0.3 on 2024-03-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_profile_options_remove_profile_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dt_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="dt_updated",
            field=models.DateTimeField(auto_now=True, db_index=True, null=True),
        ),
    ]
