# Generated by Django 5.0.3 on 2024-03-07 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_dt_created_profile_dt_updated"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="unsubiscribe",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Hash",
            fields=[
                (
                    "hash",
                    models.CharField(
                        max_length=40,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Key",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("confirm_email", "confirm_email"),
                            ("change_password", "change_password"),
                            ("unsubiscribe", "unsubiscribe"),
                        ],
                        default="confirm_email",
                        max_length=25,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Hash",
                "verbose_name_plural": "Hashes",
            },
        ),
    ]
