# Generated by Django 5.0.3 on 2024-03-07 15:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_profile_unsubiscribe_hash"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="hash",
            constraint=models.UniqueConstraint(
                fields=("user", "type"), name="unique_user_type"
            ),
        ),
    ]
