# Generated by Django 5.0.3 on 2024-03-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_rename_unsubiscribe_profile_unsubscribe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("professional_free", "professional_free"),
                    ("professional_basic", "professional_basic"),
                    ("professional_premium", "professional_premium"),
                    ("admin", "admin"),
                    ("super_admin", "super_admin"),
                ],
                default="user",
                max_length=25,
            ),
        ),
    ]
