# Generated by Django 5.0.3 on 2024-03-11 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_profile_access_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hash",
            name="hash",
            field=models.CharField(
                db_index=True,
                max_length=40,
                primary_key=True,
                serialize=False,
                verbose_name="Key",
            ),
        ),
        migrations.AlterField(
            model_name="hash",
            name="type",
            field=models.CharField(
                choices=[
                    ("confirm_email", "confirm_email"),
                    ("change_password", "change_password"),
                    ("unsubscribe", "unsubscribe"),
                ],
                db_index=True,
                default="confirm_email",
                max_length=25,
            ),
        ),
    ]
