# Generated by Django 5.0.3 on 2024-03-14 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_hash_hash_alter_hash_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="profile",
            options={"verbose_name": "Perfil", "verbose_name_plural": "Perfis"},
        ),
    ]
