# Generated by Django 5.0.3 on 2024-09-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="dt_created",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
