# Generated by Django 5.0.3 on 2024-09-23 15:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_invite_dt_created"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invite",
            old_name="email_inivited",
            new_name="email_invited",
        ),
    ]
