# Generated by Django 5.0.3 on 2025-02-13 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_rename_email_inivited_invite_email_invited"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="address",
        ),
        migrations.AlterField(
            model_name="profile",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("professional_free", "professional_free"),
                    ("professional_basic", "professional_basic"),
                    ("professional_premium", "professional_premium"),
                    ("admin", "admin"),
                    ("super_admin", "super_admin"),
                ],
                db_index=True,
                default="user",
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="AddressUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(blank=True, max_length=255, null=True)),
                ("number", models.CharField(blank=True, max_length=10, null=True)),
                ("zipcode", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "neighborhood",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                ("city", models.CharField(blank=True, max_length=120, null=True)),
                ("state", models.CharField(blank=True, max_length=120, null=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Endereço",
                "verbose_name_plural": "Endereços",
            },
        ),
        migrations.DeleteModel(
            name="Invite",
        ),
    ]
