# Generated by Django 5.0.3 on 2025-04-04 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_remove_profile_address_alter_profile_access_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="access_level",
            field=models.CharField(
                choices=[
                    ("user", "user"),
                    ("admin", "admin"),
                    ("support", "support"),
                    ("super_admin", "super_admin"),
                ],
                db_index=True,
                default="user",
                max_length=25,
            ),
        ),
    ]
