# Generated by Django 5.0.3 on 2025-04-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_alter_profile_access_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="plan",
            field=models.CharField(
                choices=[("free", "free"), ("pro", "pro"), ("admin", "admin")],
                db_index=True,
                default="free",
                max_length=25,
            ),
        ),
    ]
