# Generated by Django 5.0.3 on 2025-04-16 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ecommerce",
            "0002_remove_order_paid_order_total_price_product_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
