# Generated by Django 5.0.3 on 2025-04-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_remove_notification_is_read_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="title",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
