# Generated by Django 5.0.3 on 2025-04-09 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_alter_message_options_remove_message_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={},
        ),
        migrations.RemoveField(
            model_name="room",
            name="user1",
        ),
        migrations.RemoveField(
            model_name="room",
            name="user2",
        ),
        migrations.AddField(
            model_name="message",
            name="type_message",
            field=models.CharField(
                choices=[
                    ("text", "Texto"),
                    ("image", "Imagem"),
                    ("link", "Link"),
                    ("file", "Arquivo"),
                    ("system", "Sistema"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="users",
            field=models.ManyToManyField(
                related_name="rooms", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="content",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
